#ifndef VALUELIST_H
#define VALUELIST_H

NAME2VALUE elem_type_valuelist_array[] =
{
	{"STRING",CUBE_TYPE_STRING},
	{"UUID",CUBE_TYPE_UUID},
	{"INT",CUBE_TYPE_INT},
	{"ENUM",CUBE_TYPE_ENUM},      // a 32-bit enum
	{"SENUM",CUBE_TYPE_SENUM},      // a 16-bit enum
	{"BENUM",CUBE_TYPE_BENUM},      // an 8-bit enum
	{"FLAG",CUBE_TYPE_FLAG},	// a 32-bit flag
	{"SFLAG",CUBE_TYPE_SFLAG},	// a 16-bit flag
	{"BFLAG",CUBE_TYPE_BFLAG},	// an 8-bit flag	
	{"TIME",CUBE_TYPE_TIME},
	{"UCHAR",CUBE_TYPE_UCHAR},
	{"USHORT",CUBE_TYPE_USHORT},   // a 16-bit unsigned word
	{"LONGLONG",CUBE_TYPE_LONGLONG}, // a 64-bit longlong integer
	{"BINDATA",CUBE_TYPE_BINDATA},  // a sequence of octets with fixed size
	{"BITMAP",CUBE_TYPE_BITMAP}, 
	{"HEXDATA",CUBE_TYPE_HEXDATA},  
	{"BINARRAY",CUBE_TYPE_BINARRAY},   
	{"UUIDARRAY",CUBE_TYPE_UUIDARRAY},   
	{"DEFUUIDARRAY",CUBE_TYPE_DEFUUIDARRAY},   
	{"DEFNAMELIST",CUBE_TYPE_DEFNAMELIST},   
	{"BOOL",CUBE_TYPE_BOOL},
	{"ESTRING",CUBE_TYPE_ESTRING},
	{"JSONSTRING",CUBE_TYPE_JSONSTRING},
	{"NODATA",CUBE_TYPE_NODATA},
	{"ARRAY",CUBE_TYPE_ARRAY},
	{"DEFINE",CUBE_TYPE_DEFINE},
	{"DEFSTR",CUBE_TYPE_DEFSTR},
	{"DEFSTRARRAY",CUBE_TYPE_DEFSTRARRAY},
	{"SUBSTRUCT",CUBE_TYPE_SUBSTRUCT},
        {"CHOICE",CUBE_TYPE_CHOICE},
	{"TPM64",TPM_TYPE_UINT64},
	{"TPM32",TPM_TYPE_UINT32},
	{"TPM16",TPM_TYPE_UINT16},
	{"ENDDATA",CUBE_TYPE_ENDDATA},
    	{NULL,0}
};


NAME2VALUE memdb_elem_type_array[] =
{
    {"ELEMTYPE",CUBE_TYPE_ELEMTYPE},
    {"TYPE",CUBE_TYPE_RECORDTYPE},
    {"SUBTYPE",CUBE_TYPE_RECORDSUBTYPE},
    {NULL,0}
};


NAME2VALUE elem_attr_flaglist_array[] =
{
    {"INDEX",CUBE_ELEM_FLAG_INDEX},
    {"KEY",CUBE_ELEM_FLAG_KEY},
    {"INPUT",CUBE_ELEM_FLAG_INPUT},
    {"DESC",CUBE_ELEM_FLAG_DESC},
    {NULL,0}
};


NAME2VALUE struct_type_baselist[] =
{
    {"INDEX",DB_INDEX},
    {"NAMELIST",DB_NAMELIST},
    {"STRUCT",DB_STRUCT_DESC},
    {"TYPELIST",DB_TYPELIST},
    {"SUBTYPELIST",DB_SUBTYPELIST},
    {"CONVERTLIST",DB_CONVERTLIST},
    {"RECORDTYPE",DB_RECORDTYPE},
    {"DEFAULT",DB_DTYPE_START},
    {NULL,0}
};

#endif
