#!/bin/sh
export TCGPATH=$CUBE_TRUSTROOT_PATH
SWTPMPATH=$TCGPATH/swTPM
TPMDEVPATH=$TCGPATH/tpmd_dev
export TPM_SERVER_PORT=$1
export TPM_SERVER_NAME=127.0.0.1
export TPM_PORT=$1
export TPM_PATH=$SWTPMPATH/tpmdata/$1
#$SWTPMPATH/tpm/tpm_server &>tpm.log &
#sleep 1
#$SWTPMPATH/libtpm/utils/tpminit 
#$SWTPMPATH/libtpm/utils/tpmbios 
killall tpm_server
killall tcsd
rmmod tpmd_dev
sleep 2
$SWTPMPATH/tpm/tpm_server &>tpm.log &
sleep 1
$SWTPMPATH/libtpm/utils/tpmbios 
cd $TPMDEVPATH
./load_tpmd_dev.sh $1
tcsd
cd -
cd example
./TESI_test -v 1.2
cd -

